package demo.djz;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("DJZTrading") 
public class CStructStockDetail extends StructObject {
	static {
		BridJ.register();
	}

	/** C type : char* */
	@Field(0) 
	public Pointer<Byte> symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char* */
	@Field(0) 
	public CStructStockDetail symbol(Pointer<Byte > symbol) {
		this.io.setPointerField(this, 0, symbol);
		return this;
	}
	@Field(1) 
	public double cashPayoutRatio() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public CStructStockDetail cashPayoutRatio(double cashPayoutRatio) {
		this.io.setDoubleField(this, 1, cashPayoutRatio);
		return this;
	}
	
	@Field(2) 
	public double stockSplitRatio() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public CStructStockDetail stockSplitRatio(double stockSplitRatio) {
		this.io.setDoubleField(this, 2, stockSplitRatio);
		return this;
	}
	
	@Field(3) 
	public double stockDividendRatio() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public CStructStockDetail stockDividendRatio(double stockDividendRatio) {
		this.io.setDoubleField(this, 3, stockDividendRatio);
		return this;
	}
}
