package demo.djz;

import java.util.Date;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CStructQuote") 
@Library("DJZTrading") 
public class CStructQuote extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : char* */
	@Field(0) 
	public Pointer<Byte > instrumentId() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char* */
	@Field(0) 
	public CStructQuote instrumentId(Pointer<Byte > instrumentId) {
		this.io.setPointerField(this, 0, instrumentId);
		return this;
	}
	/** C type : char* */
	@Field(1) 
	public Pointer<Byte > exchangeId() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : char* */
	@Field(1) 
	public CStructQuote exchangeId(Pointer<Byte > exchangeId) {
		this.io.setPointerField(this, 1, exchangeId);
		return this;
	}
	@Field(2) 
	public int bidsize() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public CStructQuote bidsize(int bidsize) {
		this.io.setIntField(this, 2, bidsize);
		return this;
	}
	@Field(3) 
	public double bid() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public CStructQuote bid(double bid) {
		this.io.setDoubleField(this, 3, bid);
		return this;
	}
	@Field(4) 
	public double ask() {
		return this.io.getDoubleField(this, 4);
	}
	@Field(4) 
	public CStructQuote ask(double ask) {
		this.io.setDoubleField(this, 4, ask);
		return this;
	}
	@Field(5) 
	public int asksize() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public CStructQuote asksize(int asksize) {
		this.io.setIntField(this, 5, asksize);
		return this;
	}
	@Field(6) 
	public double last() {
		return this.io.getDoubleField(this, 6);
	}
	@Field(6) 
	public CStructQuote last(double last) {
		this.io.setDoubleField(this, 6, last);
		return this;
	}
	@Field(7) 
	public int lastsize() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public CStructQuote lastsize(int lastsize) {
		this.io.setIntField(this, 7, lastsize);
		return this;
	}
	@Field(8) 
	public double high() {
		return this.io.getDoubleField(this, 8);
	}
	@Field(8) 
	public CStructQuote high(double high) {
		this.io.setDoubleField(this, 8, high);
		return this;
	}
	@Field(9) 
	public double low() {
		return this.io.getDoubleField(this, 9);
	}
	@Field(9) 
	public CStructQuote low(double low) {
		this.io.setDoubleField(this, 9, low);
		return this;
	}
	@Field(10) 
	public int volume() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public CStructQuote volume(int volume) {
		this.io.setIntField(this, 10, volume);
		return this;
	}
	@Field(11) 
	public double close() {
		return this.io.getDoubleField(this, 11);
	}
	@Field(11) 
	public CStructQuote close(double close) {
		this.io.setDoubleField(this, 11, close);
		return this;
	}
	@Field(12) 
	public double open() {
		return this.io.getDoubleField(this, 12);
	}
	@Field(12) 
	public CStructQuote open(double open) {
		this.io.setDoubleField(this, 12, open);
		return this;
	}
	@Field(13) 
	public int openInterest() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public CStructQuote openInterest(int openInterest) {
		this.io.setIntField(this, 13, openInterest);
		return this;
	}
	@Field(14) 
	public int milliseconds() {
		return this.io.getIntField(this, 14);
	}
	@Field(14) 
	public CStructQuote milliseconds(int milliseconds) {
		this.io.setIntField(this, 14, milliseconds);
		return this;
	}
	/** C type : char* */
	@Field(15) 
	public Pointer<Byte > day() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : char* */
	@Field(15) 
	public CStructQuote day(Pointer<Byte > day) {
		this.io.setPointerField(this, 15, day);
		return this;
	}
	/** C type : char* */
	@Field(16) 
	public Pointer<Byte > time() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : char* */
	@Field(16) 
	public CStructQuote time(Pointer<Byte > time) {
		this.io.setPointerField(this, 16, time);
		return this;
	}
	/** C type : char* */
	@Field(17) 
	public Pointer<Byte > traceBegin() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : char* */
	@Field(17) 
	public CStructQuote traceBegin(Pointer<Byte > traceBegin) {
		this.io.setPointerField(this, 17, traceBegin);
		return this;
	}
	@Field(18) 
	public long receiveMillisecond() {
		return this.io.getLongField(this, 18);
	}
	@Field(18) 
	public CStructQuote receiveMillisecond(long receiveMillisecond) {
		this.io.setLongField(this, 18, receiveMillisecond);
		return this;
	}
	
	/** C type : char* */
	@Field(19) 
	public Pointer<Byte > flag() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : char* */
	@Field(19) 
	public CStructQuote flag(Pointer<Byte > flag) {
		this.io.setPointerField(this, 19, flag);
		return this;
	}	
	
/*	@Field(19) 
	public long flag() {
		return this.io.getLongField(this, 19);
	}
	@Field(19) 
	public CStructQuote flag(long flag) {
		this.io.setLongField(this, 19, flag);
		return this;
	}*/
	
	public CStructQuote() {
		super();
	}
	public CStructQuote(Pointer pointer) {
		super(pointer);
	}
	
}
