package demo.djz;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("DJZTrading") 
public class CStructPosition extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : char* */
	@Field(0) 
	public Pointer<Byte > brokerId() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char* */
	@Field(0) 
	public CStructPosition brokerId(Pointer<Byte > brokerId) {
		this.io.setPointerField(this, 0, brokerId);
		return this;
	}
	/** C type : char* */
	@Field(1) 
	public Pointer<Byte > investorId() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : char* */
	@Field(1) 
	public CStructPosition investorId(Pointer<Byte > investorId) {
		this.io.setPointerField(this, 1, investorId);
		return this;
	}
	/** C type : char* */
	@Field(2) 
	public Pointer<Byte > instrumentId() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : char* */
	@Field(2) 
	public CStructPosition instrumentId(Pointer<Byte > instrumentId) {
		this.io.setPointerField(this, 2, instrumentId);
		return this;
	}
	@Field(3) 
	public byte posiDirection() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public CStructPosition posiDirection(byte posiDirection) {
		this.io.setByteField(this, 3, posiDirection);
		return this;
	}
	@Field(4) 
	public byte positionDate() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public CStructPosition positionDate(byte positionDate) {
		this.io.setByteField(this, 4, positionDate);
		return this;
	}
	@Field(5) 
	public int position() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public CStructPosition position(int position) {
		this.io.setIntField(this, 5, position);
		return this;
	}
	@Field(6) 
	public int ydPosition() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public CStructPosition ydPosition(int ydPosition) {
		this.io.setIntField(this, 6, ydPosition);
		return this;
	}
	@Field(7) 
	public int tdPosition() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public CStructPosition tdPosition(int tdPosition) {
		this.io.setIntField(this, 7, tdPosition);
		return this;
	}
	@Field(8) 
	public double openCost() {
		return this.io.getDoubleField(this, 8);
	}
	@Field(8) 
	public CStructPosition openCost(double openCost) {
		this.io.setDoubleField(this, 8, openCost);
		return this;
	}
	/** \u5f00\u4ed3\u91cf */
	@Field(9) 
	public int openVolume() {
		return this.io.getIntField(this, 9);
	}
	/** \u5f00\u4ed3\u91cf */
	@Field(9) 
	public CStructPosition openVolume(int openVolume) {
		this.io.setIntField(this, 9, openVolume);
		return this;
	}
	/** \u5e73\u4ed3\u91cf */
	@Field(10) 
	public int closeVolume() {
		return this.io.getIntField(this, 10);
	}
	/** \u5e73\u4ed3\u91cf */
	@Field(10) 
	public CStructPosition closeVolume(int closeVolume) {
		this.io.setIntField(this, 10, closeVolume);
		return this;
	}
	/** \u5f00\u4ed3\u91d1\u989d */
	@Field(11) 
	public double openAmount() {
		return this.io.getDoubleField(this, 11);
	}
	/** \u5f00\u4ed3\u91d1\u989d */
	@Field(11) 
	public CStructPosition openAmount(double openAmount) {
		this.io.setDoubleField(this, 11, openAmount);
		return this;
	}
	/** \u5e73\u4ed3\u91d1\u989d */
	@Field(12) 
	public double closeAmount() {
		return this.io.getDoubleField(this, 12);
	}
	/** \u5e73\u4ed3\u91d1\u989d */
	@Field(12) 
	public CStructPosition closeAmount(double closeAmount) {
		this.io.setDoubleField(this, 12, closeAmount);
		return this;
	}
	/** \u591a\u5934\u51bb\u7ed3 */
	@Field(13) 
	public int longFrozen() {
		return this.io.getIntField(this, 13);
	}
	/** \u591a\u5934\u51bb\u7ed3 */
	@Field(13) 
	public CStructPosition longFrozen(int longFrozen) {
		this.io.setIntField(this, 13, longFrozen);
		return this;
	}
	/** \u7a7a\u5934\u51bb\u7ed3 */
	@Field(14) 
	public int shortFrozen() {
		return this.io.getIntField(this, 14);
	}
	/** \u7a7a\u5934\u51bb\u7ed3 */
	@Field(14) 
	public CStructPosition shortFrozen(int shortFrozen) {
		this.io.setIntField(this, 14, shortFrozen);
		return this;
	}
	/** \u5e73\u4ed3\u76c8\u4e8f */
	@Field(15) 
	public double closeProfit() {
		return this.io.getDoubleField(this, 15);
	}
	/** \u5e73\u4ed3\u76c8\u4e8f */
	@Field(15) 
	public CStructPosition closeProfit(double closeProfit) {
		this.io.setDoubleField(this, 15, closeProfit);
		return this;
	}
	/** \u6301\u4ed3\u76c8\u4e8f */
	@Field(16) 
	public double positionProfit() {
		return this.io.getDoubleField(this, 16);
	}
	/** \u6301\u4ed3\u76c8\u4e8f */
	@Field(16) 
	public CStructPosition positionProfit(double positionProfit) {
		this.io.setDoubleField(this, 16, positionProfit);
		return this;
	}
	/** \u624b\u7eed\u8d39 */
	@Field(17) 
	public double commission() {
		return this.io.getDoubleField(this, 17);
	}
	/** \u624b\u7eed\u8d39 */
	@Field(17) 
	public CStructPosition commission(double commission) {
		this.io.setDoubleField(this, 17, commission);
		return this;
	}
	public CStructPosition() {
		super();
	}
	public CStructPosition(Pointer pointer) {
		super(pointer);
	}
}
