package demo.djz;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("DJZTrading") 
public class CStructOutOrder extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int adaptorId() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public CStructOutOrder adaptorId(int adaptorId) {
		this.io.setIntField(this, 0, adaptorId);
		return this;
	}
	/** C type : char* */
	@Field(1) 
	public Pointer<Byte > brokerId() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : char* */
	@Field(1) 
	public CStructOutOrder brokerId(Pointer<Byte > brokerId) {
		this.io.setPointerField(this, 1, brokerId);
		return this;
	}
	/** C type : char* */
	@Field(2) 
	public Pointer<Byte > investorId() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : char* */
	@Field(2) 
	public CStructOutOrder investorId(Pointer<Byte > investorId) {
		this.io.setPointerField(this, 2, investorId);
		return this;
	}
	/** C type : char* */
	@Field(3) 
	public Pointer<Byte > userId() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : char* */
	@Field(3) 
	public CStructOutOrder userId(Pointer<Byte > userId) {
		this.io.setPointerField(this, 3, userId);
		return this;
	}
	@Field(4) 
	public int id() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public CStructOutOrder id(int id) {
		this.io.setIntField(this, 4, id);
		return this;
	}
	/** C type : char* */
	@Field(5) 
	public Pointer<Byte > instrumentId() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : char* */
	@Field(5) 
	public CStructOutOrder instrumentId(Pointer<Byte > instrumentId) {
		this.io.setPointerField(this, 5, instrumentId);
		return this;
	}
	@Field(6) 
	public byte status() {
		return this.io.getByteField(this, 6);
	}
	@Field(6) 
	public CStructOutOrder status(byte status) {
		this.io.setByteField(this, 6, status);
		return this;
	}
	@Field(7) 
	public double limitPrice() {
		return this.io.getDoubleField(this, 7);
	}
	@Field(7) 
	public CStructOutOrder limitPrice(double limitPrice) {
		this.io.setDoubleField(this, 7, limitPrice);
		return this;
	}
	/** C type : char* */
	@Field(8) 
	public Pointer<Byte > ref() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : char* */
	@Field(8) 
	public CStructOutOrder ref(Pointer<Byte > ref) {
		this.io.setPointerField(this, 8, ref);
		return this;
	}
	@Field(9) 
	public byte priceType() {
		return this.io.getByteField(this, 9);
	}
	@Field(9) 
	public CStructOutOrder priceType(byte priceType) {
		this.io.setByteField(this, 9, priceType);
		return this;
	}
	@Field(10) 
	public byte direction() {
		return this.io.getByteField(this, 10);
	}
	@Field(10) 
	public CStructOutOrder direction(byte direction) {
		this.io.setByteField(this, 10, direction);
		return this;
	}
	/** C type : char* */
	@Field(11) 
	public Pointer<Byte > combOffsetFlag() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : char* */
	@Field(11) 
	public CStructOutOrder combOffsetFlag(Pointer<Byte > combOffsetFlag) {
		this.io.setPointerField(this, 11, combOffsetFlag);
		return this;
	}
	/** C type : char* */
	@Field(12) 
	public Pointer<Byte > combHedgeFlag() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : char* */
	@Field(12) 
	public CStructOutOrder combHedgeFlag(Pointer<Byte > combHedgeFlag) {
		this.io.setPointerField(this, 12, combHedgeFlag);
		return this;
	}
	@Field(13) 
	public int volumeTotalOriginal() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public CStructOutOrder volumeTotalOriginal(int volumeTotalOriginal) {
		this.io.setIntField(this, 13, volumeTotalOriginal);
		return this;
	}
	@Field(14) 
	public byte timeCondition() {
		return this.io.getByteField(this, 14);
	}
	@Field(14) 
	public CStructOutOrder timeCondition(byte timeCondition) {
		this.io.setByteField(this, 14, timeCondition);
		return this;
	}
	/**
	 * not used<br>
	 * C type : char*
	 */
	@Field(15) 
	public Pointer<Byte > GTDDate() {
		return this.io.getPointerField(this, 15);
	}
	/**
	 * not used<br>
	 * C type : char*
	 */
	@Field(15) 
	public CStructOutOrder GTDDate(Pointer<Byte > GTDDate) {
		this.io.setPointerField(this, 15, GTDDate);
		return this;
	}
	/** not used */
	@Field(16) 
	public byte volumeCondition() {
		return this.io.getByteField(this, 16);
	}
	/** not used */
	@Field(16) 
	public CStructOutOrder volumeCondition(byte volumeCondition) {
		this.io.setByteField(this, 16, volumeCondition);
		return this;
	}
	@Field(17) 
	public int minVolume() {
		return this.io.getIntField(this, 17);
	}
	@Field(17) 
	public CStructOutOrder minVolume(int minVolume) {
		this.io.setIntField(this, 17, minVolume);
		return this;
	}
	@Field(18) 
	public byte contingentCondition() {
		return this.io.getByteField(this, 18);
	}
	@Field(18) 
	public CStructOutOrder contingentCondition(byte contingentCondition) {
		this.io.setByteField(this, 18, contingentCondition);
		return this;
	}
	@Field(19) 
	public double stopPrice() {
		return this.io.getDoubleField(this, 19);
	}
	@Field(19) 
	public CStructOutOrder stopPrice(double stopPrice) {
		this.io.setDoubleField(this, 19, stopPrice);
		return this;
	}
	@Field(20) 
	public byte forceCloseReason() {
		return this.io.getByteField(this, 20);
	}
	@Field(20) 
	public CStructOutOrder forceCloseReason(byte forceCloseReason) {
		this.io.setByteField(this, 20, forceCloseReason);
		return this;
	}
	@Field(21) 
	public int isAutoSuspend() {
		return this.io.getIntField(this, 21);
	}
	@Field(21) 
	public CStructOutOrder isAutoSuspend(int isAutoSuspend) {
		this.io.setIntField(this, 21, isAutoSuspend);
		return this;
	}
	/**
	 * not used<br>
	 * C type : char*
	 */
	@Field(22) 
	public Pointer<Byte > businessUnit() {
		return this.io.getPointerField(this, 22);
	}
	/**
	 * not used<br>
	 * C type : char*
	 */
	@Field(22) 
	public CStructOutOrder businessUnit(Pointer<Byte > businessUnit) {
		this.io.setPointerField(this, 22, businessUnit);
		return this;
	}
	/** notused */
	@Field(23) 
	public int requestId() {
		return this.io.getIntField(this, 23);
	}
	/** notused */
	@Field(23) 
	public CStructOutOrder requestId(int requestId) {
		this.io.setIntField(this, 23, requestId);
		return this;
	}
	@Field(24) 
	public int userForceClose() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public CStructOutOrder userForceClose(int userForceClose) {
		this.io.setIntField(this, 24, userForceClose);
		return this;
	}
	/** C type : char* */
	@Field(25) 
	public Pointer<Byte > localId() {
		return this.io.getPointerField(this, 25);
	}
	/** C type : char* */
	@Field(25) 
	public CStructOutOrder localId(Pointer<Byte > localId) {
		this.io.setPointerField(this, 25, localId);
		return this;
	}
	/** C type : char* */
	@Field(26) 
	public Pointer<Byte > exchangeId() {
		return this.io.getPointerField(this, 26);
	}
	/** C type : char* */
	@Field(26) 
	public CStructOutOrder exchangeId(Pointer<Byte > exchangeId) {
		this.io.setPointerField(this, 26, exchangeId);
		return this;
	}
	/** C type : char* */
	@Field(27) 
	public Pointer<Byte > participantID() {
		return this.io.getPointerField(this, 27);
	}
	/** C type : char* */
	@Field(27) 
	public CStructOutOrder participantID(Pointer<Byte > participantID) {
		this.io.setPointerField(this, 27, participantID);
		return this;
	}
	/** C type : char* */
	@Field(28) 
	public Pointer<Byte > clientId() {
		return this.io.getPointerField(this, 28);
	}
	/** C type : char* */
	@Field(28) 
	public CStructOutOrder clientId(Pointer<Byte > clientId) {
		this.io.setPointerField(this, 28, clientId);
		return this;
	}
	/** C type : char* */
	@Field(29) 
	public Pointer<Byte > exchangeInstId() {
		return this.io.getPointerField(this, 29);
	}
	/** C type : char* */
	@Field(29) 
	public CStructOutOrder exchangeInstId(Pointer<Byte > exchangeInstId) {
		this.io.setPointerField(this, 29, exchangeInstId);
		return this;
	}
	/** C type : char* */
	@Field(30) 
	public Pointer<Byte > traderId() {
		return this.io.getPointerField(this, 30);
	}
	/** C type : char* */
	@Field(30) 
	public CStructOutOrder traderId(Pointer<Byte > traderId) {
		this.io.setPointerField(this, 30, traderId);
		return this;
	}
	@Field(31) 
	public int installId() {
		return this.io.getIntField(this, 31);
	}
	@Field(31) 
	public CStructOutOrder installId(int installId) {
		this.io.setIntField(this, 31, installId);
		return this;
	}
	@Field(32) 
	public byte orderSubmitStatus() {
		return this.io.getByteField(this, 32);
	}
	@Field(32) 
	public CStructOutOrder orderSubmitStatus(byte orderSubmitStatus) {
		this.io.setByteField(this, 32, orderSubmitStatus);
		return this;
	}
	@Field(33) 
	public int notifySequence() {
		return this.io.getIntField(this, 33);
	}
	@Field(33) 
	public CStructOutOrder notifySequence(int notifySequence) {
		this.io.setIntField(this, 33, notifySequence);
		return this;
	}
	/** C type : char* */
	@Field(34) 
	public Pointer<Byte > tradingDay() {
		return this.io.getPointerField(this, 34);
	}
	/** C type : char* */
	@Field(34) 
	public CStructOutOrder tradingDay(Pointer<Byte > tradingDay) {
		this.io.setPointerField(this, 34, tradingDay);
		return this;
	}
	@Field(35) 
	public int settlementId() {
		return this.io.getIntField(this, 35);
	}
	@Field(35) 
	public CStructOutOrder settlementId(int settlementId) {
		this.io.setIntField(this, 35, settlementId);
		return this;
	}
	/** char *orderSysID; */
	@Field(36) 
	public byte source() {
		return this.io.getByteField(this, 36);
	}
	/** char *orderSysID; */
	@Field(36) 
	public CStructOutOrder source(byte source) {
		this.io.setByteField(this, 36, source);
		return this;
	}
	@Field(37) 
	public byte type() {
		return this.io.getByteField(this, 37);
	}
	@Field(37) 
	public CStructOutOrder type(byte type) {
		this.io.setByteField(this, 37, type);
		return this;
	}
	@Field(38) 
	public int volumeTraded() {
		return this.io.getIntField(this, 38);
	}
	@Field(38) 
	public CStructOutOrder volumeTraded(int volumeTraded) {
		this.io.setIntField(this, 38, volumeTraded);
		return this;
	}
	@Field(39) 
	public int volumeTotal() {
		return this.io.getIntField(this, 39);
	}
	@Field(39) 
	public CStructOutOrder volumeTotal(int volumeTotal) {
		this.io.setIntField(this, 39, volumeTotal);
		return this;
	}
	/** C type : char* */
	@Field(40) 
	public Pointer<Byte > insertDate() {
		return this.io.getPointerField(this, 40);
	}
	/** C type : char* */
	@Field(40) 
	public CStructOutOrder insertDate(Pointer<Byte > insertDate) {
		this.io.setPointerField(this, 40, insertDate);
		return this;
	}
	/** C type : char* */
	@Field(41) 
	public Pointer<Byte > insertTime() {
		return this.io.getPointerField(this, 41);
	}
	/** C type : char* */
	@Field(41) 
	public CStructOutOrder insertTime(Pointer<Byte > insertTime) {
		this.io.setPointerField(this, 41, insertTime);
		return this;
	}
	/** C type : char* */
	@Field(42) 
	public Pointer<Byte > activeTime() {
		return this.io.getPointerField(this, 42);
	}
	/** C type : char* */
	@Field(42) 
	public CStructOutOrder activeTime(Pointer<Byte > activeTime) {
		this.io.setPointerField(this, 42, activeTime);
		return this;
	}
	/** C type : char* */
	@Field(43) 
	public Pointer<Byte > suspendTime() {
		return this.io.getPointerField(this, 43);
	}
	/** C type : char* */
	@Field(43) 
	public CStructOutOrder suspendTime(Pointer<Byte > suspendTime) {
		this.io.setPointerField(this, 43, suspendTime);
		return this;
	}
	/** C type : char* */
	@Field(44) 
	public Pointer<Byte > updateTime() {
		return this.io.getPointerField(this, 44);
	}
	/** C type : char* */
	@Field(44) 
	public CStructOutOrder updateTime(Pointer<Byte > updateTime) {
		this.io.setPointerField(this, 44, updateTime);
		return this;
	}
	/** C type : char* */
	@Field(45) 
	public Pointer<Byte > cancelTime() {
		return this.io.getPointerField(this, 45);
	}
	/** C type : char* */
	@Field(45) 
	public CStructOutOrder cancelTime(Pointer<Byte > cancelTime) {
		this.io.setPointerField(this, 45, cancelTime);
		return this;
	}
	/** C type : char* */
	@Field(46) 
	public Pointer<Byte > activeTraderId() {
		return this.io.getPointerField(this, 46);
	}
	/** C type : char* */
	@Field(46) 
	public CStructOutOrder activeTraderId(Pointer<Byte > activeTraderId) {
		this.io.setPointerField(this, 46, activeTraderId);
		return this;
	}
	/** C type : char* */
	@Field(47) 
	public Pointer<Byte > clearingPartId() {
		return this.io.getPointerField(this, 47);
	}
	/** C type : char* */
	@Field(47) 
	public CStructOutOrder clearingPartId(Pointer<Byte > clearingPartId) {
		this.io.setPointerField(this, 47, clearingPartId);
		return this;
	}
	@Field(48) 
	public int sequenceNo() {
		return this.io.getIntField(this, 48);
	}
	@Field(48) 
	public CStructOutOrder sequenceNo(int sequenceNo) {
		this.io.setIntField(this, 48, sequenceNo);
		return this;
	}
	@Field(49) 
	public int frontId() {
		return this.io.getIntField(this, 49);
	}
	@Field(49) 
	public CStructOutOrder frontId(int frontId) {
		this.io.setIntField(this, 49, frontId);
		return this;
	}
	@Field(50) 
	public int sessionId() {
		return this.io.getIntField(this, 50);
	}
	@Field(50) 
	public CStructOutOrder sessionId(int sessionId) {
		this.io.setIntField(this, 50, sessionId);
		return this;
	}
	/** C type : char* */
	@Field(51) 
	public Pointer<Byte > userProductInfo() {
		return this.io.getPointerField(this, 51);
	}
	/** C type : char* */
	@Field(51) 
	public CStructOutOrder userProductInfo(Pointer<Byte > userProductInfo) {
		this.io.setPointerField(this, 51, userProductInfo);
		return this;
	}
	/** C type : char* */
	@Field(52) 
	public Pointer<Byte > statusMsg() {
		return this.io.getPointerField(this, 52);
	}
	/** C type : char* */
	@Field(52) 
	public CStructOutOrder statusMsg(Pointer<Byte > statusMsg) {
		this.io.setPointerField(this, 52, statusMsg);
		return this;
	}
	/** C type : char* */
	@Field(53) 
	public Pointer<Byte > activeUserId() {
		return this.io.getPointerField(this, 53);
	}
	/** C type : char* */
	@Field(53) 
	public CStructOutOrder activeUserId(Pointer<Byte > activeUserId) {
		this.io.setPointerField(this, 53, activeUserId);
		return this;
	}
	@Field(54) 
	public int brokerOrderSeq() {
		return this.io.getIntField(this, 54);
	}
	@Field(54) 
	public CStructOutOrder brokerOrderSeq(int brokerOrderSeq) {
		this.io.setIntField(this, 54, brokerOrderSeq);
		return this;
	}
	/** C type : char* */
	@Field(55) 
	public Pointer<Byte > sysId() {
		return this.io.getPointerField(this, 55);
	}
	/** C type : char* */
	@Field(55) 
	public CStructOutOrder sysId(Pointer<Byte > sysId) {
		this.io.setPointerField(this, 55, sysId);
		return this;
	}
	@Field(56) 
	public int isLast() {
		return this.io.getIntField(this, 56);
	}
	@Field(56) 
	public CStructOutOrder isLast(int isLast) {
		this.io.setIntField(this, 56, isLast);
		return this;
	}
	@Field(57) 
	public long updateMillisecond() {
		return this.io.getLongField(this, 57);
	}
	@Field(57) 
	public CStructOutOrder updateMillisecond(long updateMillisecond) {
		this.io.setLongField(this, 57, updateMillisecond);
		return this;
	}
	public CStructOutOrder() {
		super();
	}
	public CStructOutOrder(Pointer pointer) {
		super(pointer);
	}
}
